# Generated by Django 3.2.4 on 2024-03-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Id',
            new_name='id',
        ),
    ]
