# Generated by Django 4.2.11 on 2024-03-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_id_contact_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('Created_date',)},
        ),
    ]
