# Generated by Django 3.2.4 on 2024-03-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='Created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='Publish_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Id',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
