# Generated by Django 3.2.4 on 2024-03-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240324_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update_date',
            new_name='Updated_date',
        ),
    ]
