# Generated by Django 3.2.4 on 2024-03-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_update_date_post_updated_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
