# Generated by Django 3.2.4 on 2024-03-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.TextField()),
                ('Publish_date', models.DateField()),
                ('Created_date', models.DateField(auto_now_add=True)),
                ('Updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
