# Generated by Django 3.2.4 on 2024-03-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('Created_date',)},
        ),
        migrations.AddField(
            model_name='post',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
