# Generated by Django 3.2.4 on 2024-03-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240325_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Counted_Views',
            field=models.IntegerField(default=0),
        ),
    ]
