# Generated by Django 4.2.11 on 2024-03-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_counted_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='Publish_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='post',
            name='Tags',
            field=models.IntegerField(default=0),
        ),
    ]
