# Generated by Django 4.2.11 on 2024-03-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='Blog/default.jpg', upload_to='Blog/Images'),
        ),
    ]
