# Generated by Django 4.2.11 on 2024-03-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='Blog/Images'),
        ),
    ]
