# Generated by Django 4.2.11 on 2024-03-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Image',
        ),
    ]
