# Generated by Django 4.2.11 on 2024-03-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_category_remove_post_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
