# Generated by Django 4.2.13 on 2024-05-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Publish_time',
        ),
        migrations.AlterField(
            model_name='post',
            name='Created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Publish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='Updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
